# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('klubevents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date event was created'),
        ),
    ]
