# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klubevents', '0002_event_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_notes',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='event',
            name='preamble',
            field=models.CharField(default='', max_length=512),
        ),
    ]
