# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('klubevents', '0003_auto_20170529_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='additional_notes',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='event',
            name='number',
            field=models.IntegerField(verbose_name='event #'),
        ),
        migrations.AlterField(
            model_name='event',
            name='preamble',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
